import type { Metadata } from 'next';

import { MainNav } from '@/components/main-nav';

import { HeroUIProvider } from '@heroui/system';
import { ThemeProvider } from '@/components/theme-provider';
import { withProviders } from './providers';
import ReduxProvider from '@/store/redux-provider';

import { cn } from '@/utils/styles';

import '../styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const Providers = withProviders(HeroUIProvider, ThemeProvider, ReduxProvider);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn('min-h-screen bg-background font-sans antialiased')}>
        <Providers>
          <MainNav />
          <div className="border-border/40 dark:border-border mx-auto w-full min-[1800px]:max-w-[1536px] min-[1800px]:border-x">
            <main className="flex-1">
              <div className="relative flex min-h-screen flex-col bg-background p-12">
                {children}
              </div>
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
